### ISSUE TITLE
Can you make send message as someone else next?

### ISSUE THREAD

**Issue by Minacat1** [Discord-Toolkit-Official/Discord-Toolkit-Public#2]
Plz??

**Comment by Minacat1** [comment]
@TRH-Raz @Wang-sus @tungdo0602 @tungdo0602 @Raz-js

**Comment by Raz-js** [comment]
> @TRH-Raz @Wang-sus @tungdo0602 @tungdo0602 @Raz-js

Don't ping all devs as its blantantly disrespectful, wait for a response

**Comment by Raz-js** [comment]
And yes you can, although its local and not viewable by others and don't ask us to add that as its physically impossible
